language: php

services:
  - elasticsearch

php:
  - 7.3
  - 7.4

env:
  - ELASTICSEARCH_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb

before_install:
  # Disable XDebug speed up test execution.
  - phpenv config-rm xdebug.ini || return 0
  - curl ${ELASTICSEARCH_DOWNLOAD_URL} -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

install:
  - make dependencies

script:
  - make test
  - make qa
  - make changelog
