language: php

sudo: true

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: ES_VERSION="2.4.4"
    - php: 7.1
      env: ES_VERSION="1.7.6" DOWNLOAD_URL="https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.deb"
    - php: hhvm
  allow_failures:
    - php: hhvm

env:
  global:
    - ES_VERSION="2.4.4"
    - DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.deb"

before_install:
  - curl -O $DOWNLOAD_URL && sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb && sudo service elasticsearch restart
  - phpenv config-rm xdebug.ini || return 0
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
  - travis_retry composer self-update
  - travis_retry composer install --ignore-platform-reqs
  - composer info -i

script:
  - phpunit --exclude-group=none

branches:
  only:
    - master
